name: build

on:
  push:
    branches-ignore:
      - deploy
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: run services
        run: make services-ci
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install
      - name: check version
        run: make test-version
      - name: run linters
        run: make lint-check
      - name: run tests
        run: make test
      - name: upload coverage
        if: matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.xml
      - name: publish
        if: ${{ matrix.python-version == '3.12' && github.event.head_commit.message == 'release' }}
        run: make publish
